Attempt to support the HymoFS meta module upstream:https://github.com/Anatdx/hymo

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -246,7 +246,7 @@ jobs:
                   echo "BRANCH=-s stable" >> $GITHUB_ENV
                   ;;
                 "SukiSU")
-                  echo "BRANCH=-s builtin" >> $GITHUB_ENV
+                  echo "BRANCH=-s tmp-builtin" >> $GITHUB_ENV
                   ;;
                 *)
                   echo "BRANCH=-" >> $GITHUB_ENV
@@ -379,7 +379,33 @@ jobs:
             cp ../../zzh_patch/5.10-patch/fdinfo.c.patch ./
             patch -p1 < fdinfo.c.patch
           fi
-  
+      - name: HymoFS 补丁
+        if: ${{ inputs.android_version == 'android14' || inputs.android_version == 'android15' }}
+        run: |
+          cd "$CONFIG/common"
+          VERSION="${{ inputs.android_version }}"
+
+          echo "Detected Version: $VERSION"
+
+          if [ "$VERSION" = "android14" ]; then
+          # 6.1
+            echo "对 GKI 6.1 进行补丁"
+            wget https://raw.githubusercontent.com/Anatdx/HymoFS/refs/heads/android14_6.1/patch/hymofs_with_susfs.patch
+            patch -p1 -F 3 < hymofs_with_susfs.patch
+            echo "CONFIG_HYMOFS=y" >> arch/arm64/configs/gki_defconfig
+          elif [ "$VERSION" = "android15" ]; then
+          # 6.6
+            echo "对 GKI 6.6 进行补丁"
+            wget https://raw.githubusercontent.com/Anatdx/HymoFS/refs/heads/android15_6.6/patch/hymofs_with_susfs.patch
+            patch -p1 -F 3 < hymofs_with_susfs.patch
+            echo "CONFIG_HYMOFS=y" >> arch/arm64/configs/gki_defconfig
+           
+            sed -i 's/static dev_t get_dev_for_path/static dev_t __attribute__((unused)) get_dev_for_path/' fs/hymofs.c
+          else
+            echo "Error: Unsupported version: $VERSION"
+            exit 1
+          fi
+
       - name: 一些修复补丁
         run: |
           cd "$CONFIG/common"
@@ -415,6 +441,8 @@ jobs:
             fi
           fi
       
+          
+
       - name: 升级LZ4至1.10.0
         if: ${{ inputs.use_zram }}
         run: |
